<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.8</version>
        <relativePath/> 
    </parent>
    
    <groupId>com.ariesdb</groupId>
    <artifactId>ariesdb-parent</artifactId> <!-- Suffix added for clarity -->
    <version>0.0.1-SNAPSHOT</version>
    
    <!-- 1. CRITICAL: Marks this as a multi-module container -->
    <packaging>pom</packaging> 

    <name>AriesDB</name>
    <description>A disk-backed relational storage engine built from scratch.</description>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer>
            <name>Ramachandran N K</name>
        </developer>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>

    <!-- 2. CRITICAL: Defines the sub-modules -->
    <modules>
        <module>aries-core</module>
        <module>aries-engine-heap</module>
        <module>aries-cli</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <spring-shell.version>4.0.2</spring-shell.version>
    </properties>

    <!-- 3. CRITICAL: Global version management only. Actual dependencies move to aries-cli -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.shell</groupId>
                <artifactId>spring-shell-dependencies</artifactId>
                <version>${spring-shell.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>